/**
 * App Router native sitemap — split per locale via generateSitemaps().
 *
 * Generates:
 *   /sitemap/en.xml  — all English pages
 *   /sitemap/fr.xml  — all French pages
 *   /sitemap.xml     — sitemap index (auto-generated by Next.js)
 *
 * Priority tiers (per Section 9.1):
 *   1.0  — homepages
 *   0.9  — city hub pages
 *   0.8  — city + category pages
 *   0.7  — seasonal hubs
 *   0.6  — editorial guides
 *   0.3  — about, privacy
 */

import { MetadataRoute } from 'next';
import {
  getAllCities,
  getAllCategories,
  LOCALES,
  SEASONS,
} from '@/lib/data';
import {
  canonicalHomeUrl,
  canonicalCityUrl,
  canonicalCategoryUrl,
  canonicalSeasonalUrl,
  buildAlternateUrls,
} from '@/lib/urls';

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://myactivity.ca';

// Sitemap is split into two IDs: 'en' and 'fr'
export async function generateSitemaps() {
  return LOCALES.map((id) => ({ id }));
}

export default async function sitemap({
  id,
}: {
  id: string;
}): Promise<MetadataRoute.Sitemap> {
  const locale = id as 'en' | 'fr';
  const cities = getAllCities();
  const categories = getAllCategories();
  const now = new Date().toISOString();

  const entries: MetadataRoute.Sitemap = [];

  // ─── Homepage ──────────────────────────────────────────────────────────────
  entries.push({
    url: canonicalHomeUrl(locale),
    lastModified: now,
    changeFrequency: 'daily',
    priority: 1.0,
    alternates: buildAlternateUrls(
      canonicalHomeUrl(locale),
      canonicalHomeUrl('en'),
      canonicalHomeUrl('fr'),
    ),
  });

  // ─── City hub pages ────────────────────────────────────────────────────────
  for (const city of cities) {
    entries.push({
      url: canonicalCityUrl(locale, city.slug),
      lastModified: now,
      changeFrequency: 'weekly',
      priority: 0.9,
      alternates: buildAlternateUrls(
        canonicalCityUrl(locale, city.slug),
        canonicalCityUrl('en', city.slug),
        canonicalCityUrl('fr', city.slug),
      ),
    });

    // ─── City + category pages ───────────────────────────────────────────────
    for (const category of categories) {
      entries.push({
        url: canonicalCategoryUrl(locale, city.slug, category.slug),
        lastModified: now,
        changeFrequency: 'weekly',
        priority: 0.8,
        alternates: buildAlternateUrls(
          canonicalCategoryUrl(locale, city.slug, category.slug),
          canonicalCategoryUrl('en', city.slug, category.slug),
          canonicalCategoryUrl('fr', city.slug, category.slug),
        ),
      });
    }

    // ─── Seasonal hubs ───────────────────────────────────────────────────────
    for (const season of SEASONS) {
      const enUrl = `${SITE_URL}/en/seasonal/${season}-${city.slug}`;
      const frUrl = `${SITE_URL}/fr/saison/${season}-${city.slug}`;
      const canonicalUrl = locale === 'fr' ? frUrl : enUrl;

      entries.push({
        url: canonicalUrl,
        lastModified: now,
        changeFrequency: 'monthly',
        priority: 0.7,
        alternates: buildAlternateUrls(canonicalUrl, enUrl, frUrl),
      });
    }
  }

  // ─── Static pages ──────────────────────────────────────────────────────────
  for (const slug of ['about']) {
    const url = `${SITE_URL}/${locale}/${slug}`;
    entries.push({
      url,
      lastModified: now,
      changeFrequency: 'yearly',
      priority: 0.3,
      alternates: buildAlternateUrls(
        url,
        `${SITE_URL}/en/${slug}`,
        `${SITE_URL}/fr/${slug}`,
      ),
    });
  }

  return entries;
}
